steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-f"
      - "Dockerfile"
      - "--build-arg"
      - "NEXT_PUBLIC_SITE_URL=${_SITE_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_GOOGLE_ADS_CLIENT=${_ADS_CLIENT}"
      - "--build-arg"
      - "NEXT_PUBLIC_GOOGLE_ADS_SLOT=${_ADS_SLOT}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lucky-draw:latest"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lucky-draw:latest"
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - lucky-draw
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lucky-draw:latest"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - managed
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "256Mi"
      - "--max-instances"
      - "3"
      - "--project"
      - "$PROJECT_ID"

substitutions:
  _REGION: asia-east1
  _SITE_URL: https://lucky-draw-u5bq4dbqdq-de.a.run.app
  _ADS_CLIENT: ca-pub-9537577150806292
  _ADS_SLOT: "2130099221"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lucky-draw:latest"

options:
  logging: CLOUD_LOGGING_ONLY
